# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

steps:
- task: Checkmarx AST@2
  inputs:
    CheckmarxService: 'ASTConnection'
    projectName: 'WebGoatTest'
    branchName: '$(Build.SourceBranchName)'
    tenantName: 'chandra-ast-demo'
    additionalParams: '-s https://github.com/CMaheshBL/WebGoat/tree/develop/webgoat-server/src/main/java/org/owasp/webgoat   --debug'